Add swagger support
redhat-cop/spring-rest pull request #5
Opened 2018-01-17 16:05 UTC by malacourse

Please review this request to add swagger support to the spring rest sample.

2018-01-17 21:47 UTC, etsauer requested changes
@malacourse the code looks good, builds and runs properly. However, now when I run the app and hit `localhost:8080/` I get this generic error message saying there's nothing here:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jan 17 16:46:23 EST 2018
There was an unexpected error (type=Not Found, status=404).
No message available
```

Can we put something there? Maybe a mapping of API versions or something more helpful?

2018-01-18 15:14 UTC, malacourse commented
I updated code so the default path "/" returns available paths.

2018-01-18 15:44 UTC, etsauer commented
@malacourse @sabre1041 I think we should quickly align on version numbers and how they will progress, and how we want to keep them in sync between the API versions and the package version from maven.

Currently the maven `<version/>` is set at `0.1.0` and we haven't changed it since the start. The API version in this PR is `v2`. Since we are aiming to use this app to demonstrate some _real world_ application operations, I would like us to settle on a versioning strategy for this app.

Thoughts?

2018-01-20 00:38 UTC, etsauer requested changes

2018-01-20 00:38 UTC, etsauer commented on src/main/java/hello/Application.java
> +                regex("/v2/greeting.*"),
this file still has several references to v2

2018-01-22 15:16 UTC, etsauer approved these changes
LGTM

2018-01-22 15:16 UTC, merged